### ISSUE TITLE
Warning/Error file upload messages have duplicate text

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#164] opened 2019-07-10 21:11 UTC
# OCWA Issue

## User Story
**As a** _requester_,<br>
**I want** _clear error/warning messages_<br>
**so that** _I can more easily understand what I need to fix with my request_.

### ENV

- [X] `DEV`
- [ ] `TEST`
- [ ] `PROD`

### TESTCASE

1. Create a new request
2. Upload a file with study ids in it
3. Refresh the page so that the error icon displays

### EXPECTED
The error message text would be very clear and understandable.

### ACTUAL
The error message is listed twice unnecessarily.  It's also a bit weird how the "Failed" is prefixed to the error message.  Having a colon between "Failed" and the error message would be clearer.
<img width="479" alt="Annotation 2019-07-10 140623" src="https://user-images.githubusercontent.com/33532439/61005229-aa1dc400-a31c-11e9-9af8-f64a74fdbfa7.png">

**Comment by Jonesy** [comment] 2019-07-18 20:54
I have added some measures to prevent duplicate strings from being rendered here, but I think this is could more likely caused by the checkers in the API returning the same string in the `message` and `error` properties of the status object. The string fixes are in the `hotfix/form-and-text-fixes` which should be merged soon.

**Closed** 2019-09-17 18:55 UTC
Labels: enhancement
